version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile:  Dockerfile
    container_name: solar-postgres
    networks:
      - solar_network
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
